"""
Django settings for the SIGAUD project (package Python « DevArchive »).

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-(*_f)ohmf&-iu@hlyz)epl!xu=p=w0%g@ghml=1_#7d4yt23__",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").strip().lower() in {"1", "true", "yes", "on"}

# Local + simulation « déploiement » via ngrok (*.ngrok-free.app, *.ngrok-free.dev, *.ngrok.io).
# Surcharge optionnelle : variable d'environnement DJANGO_ALLOWED_HOSTS (liste séparée par des virgules).
_default_allowed = "127.0.0.1,localhost,.ngrok-free.app,.ngrok-free.dev,.ngrok.io"
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", _default_allowed).split(",")
    if h.strip()
]

# Après avoir lancé ngrok, si les formulaires renvoient une erreur CSRF (403), définir l’URL publique :
#   PowerShell : $env:DJANGO_CSRF_TRUSTED_ORIGINS="https://VOTRE-SOUS-DOMAINE.ngrok-free.dev"
#   (ou .ngrok-free.app selon l’URL affichée par ngrok)
# (repérer l’URL dans la fenêtre ngrok, onglet « Forwarding ».)
_trusted = os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").strip()
CSRF_TRUSTED_ORIGINS = [x.strip() for x in _trusted.split(",") if x.strip()]

# Derrière ngrok (HTTPS), les en-têtes X-Forwarded-* sont utiles pour les URL absolues.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'DevArchive.middleware.AppendNgrokCsrfTrustedOriginMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DevArchive.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'DevArchive' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DevArchive.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DJANGO_DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.environ.get('DJANGO_DB_NAME', 'base_devarchive'),
        'USER': os.environ.get('DJANGO_DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DJANGO_DB_PASSWORD', '353671'),
        'HOST': os.environ.get('DJANGO_DB_HOST', 'localhost'),
        'PORT': os.environ.get('DJANGO_DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Connexion : accepter email ou username (insensible à la casse)
AUTHENTICATION_BACKENDS = [
    "accounts.backend.EmailOuUsernameBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# URL dédiée de connexion administrateur (à garder confidentielle).
# Peut être surchargée via DJANGO_ADMIN_LOGIN_PATH, ex: "acces/adm-9x7k1q".
ADMIN_LOGIN_PATH = os.environ.get("DJANGO_ADMIN_LOGIN_PATH", "connexion/administrateur-prive-9x7k1q")

# Limitation des tentatives de connexion (utilisée sur les vues admin/personnel).
LOGIN_ATTEMPT_LIMIT_MAX = int(os.environ.get("DJANGO_LOGIN_ATTEMPT_LIMIT_MAX", "5"))
LOGIN_ATTEMPT_LIMIT_WINDOW_SECONDS = int(
    os.environ.get("DJANGO_LOGIN_ATTEMPT_LIMIT_WINDOW_SECONDS", "900")
)




# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Emplacement des fichiers statiques (CSS, JS, images) du projet
STATICFILES_DIRS = [
    BASE_DIR / 'DevArchive' / 'static',
]

# Fichiers uploadés (PDF d'archives, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = os.environ.get("DJANGO_EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("DJANGO_EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("DJANGO_EMAIL_USE_TLS", "true").strip().lower() in {"1", "true", "yes", "on"}
EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_HOST_USER", "ayoubatteyeh0@gmail.com")
EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_HOST_PASSWORD", "jzqwbujinupmrfic")
DEFAULT_FROM_EMAIL = os.environ.get("DJANGO_DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)