# Generated by Django 6.0.3 on 2026-03-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_faculte_sciences_filieres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='niveau',
            constraint=models.UniqueConstraint(fields=('faculte', 'code'), name='unique_niveau_code_par_faculte'),
        ),
    ]
