# Generated by Django 6.0.3 on 2026-03-07 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_niveau_code_unique_par_faculte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NiveauAccreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Niveau d'accréditation",
                'verbose_name_plural': "Niveaux d'accréditation",
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PermissionSpeciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Permission spéciale',
                'verbose_name_plural': 'Permissions spéciales',
            },
        ),
        migrations.CreateModel(
            name='ZoneResponsabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Zone de responsabilité',
                'verbose_name_plural': 'Zones de responsabilité',
            },
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('notifications_actives', models.BooleanField(default=True)),
                ('signature_admin', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administration', to=settings.AUTH_USER_MODEL)),
                ('niveau_accreditation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrations', to='accounts.niveauaccreditation')),
                ('permissions_speciales', models.ManyToManyField(blank=True, related_name='administrations', to='accounts.permissionspeciale', verbose_name='Permissions spéciales')),
                ('zone_responsabilite', models.ManyToManyField(blank=True, related_name='administrations', to='accounts.zoneresponsabilite', verbose_name='Zones de responsabilité')),
            ],
            options={
                'verbose_name': 'Administration',
                'verbose_name_plural': 'Administrations',
            },
        ),
        migrations.CreateModel(
            name='JournalAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('administration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounts.administration')),
            ],
            options={
                'verbose_name': 'Entrée du journal admin',
                'verbose_name_plural': 'Journal admin',
                'ordering': ['-date_action'],
            },
        ),
    ]
