# Generated by Django 6.0.3 on 2026-03-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_administration_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administration',
            name='niveau_accreditation',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='permissions_speciales',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='zone_responsabilite',
        ),
        migrations.RemoveField(
            model_name='journaladmin',
            name='administration',
        ),
        migrations.RemoveConstraint(
            model_name='niveau',
            name='unique_niveau_code_par_faculte',
        ),
        migrations.AlterField(
            model_name='niveau',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='NiveauAccreditation',
        ),
        migrations.DeleteModel(
            name='PermissionSpeciale',
        ),
        migrations.DeleteModel(
            name='ZoneResponsabilite',
        ),
        migrations.DeleteModel(
            name='Administration',
        ),
        migrations.DeleteModel(
            name='JournalAdmin',
        ),
    ]
