# Generated by Django 6.0.3 on 2026-03-07 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_readmin_administration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CC', 'Contrôle Continu'), ('Examen Final', 'Examen Final')], max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('module', models.CharField(max_length=150, verbose_name='Module')),
                ('filiere', models.CharField(max_length=150, verbose_name='Filière')),
                ('annee', models.CharField(max_length=20, verbose_name='Année universitaire')),
                ('session', models.CharField(blank=True, default='Normale', max_length=20)),
                ('semestre', models.CharField(blank=True, default='S1', max_length=10)),
                ('remarque', models.TextField(blank=True)),
                ('date_archive', models.DateField(auto_now_add=True, verbose_name='Archivé le')),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Archives',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('type_fichier', models.CharField(max_length=50)),
                ('chemin_fichier', models.CharField(max_length=500)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_publication', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
            },
        ),
        migrations.CreateModel(
            name='TypeExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': "Type d'examen",
                'verbose_name_plural': "Types d'examen",
            },
        ),
        migrations.RemoveField(
            model_name='administration',
            name='niveau_accreditation',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='permissions_speciales',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='zone_responsabilite',
        ),
        migrations.RemoveField(
            model_name='journaladmin',
            name='administration',
        ),
        migrations.RemoveConstraint(
            model_name='niveau',
            name='unique_niveau_code_par_faculte',
        ),
        migrations.AlterField(
            model_name='niveau',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examen',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examen',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examens', to='accounts.niveau'),
        ),
        migrations.AddField(
            model_name='document',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.examen'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matieres', to='accounts.filiere'),
        ),
        migrations.AddField(
            model_name='examen',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examens', to='accounts.matiere'),
        ),
        migrations.AddField(
            model_name='examen',
            name='type_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examens', to='accounts.typeexamen'),
        ),
        migrations.DeleteModel(
            name='NiveauAccreditation',
        ),
        migrations.DeleteModel(
            name='PermissionSpeciale',
        ),
        migrations.DeleteModel(
            name='ZoneResponsabilite',
        ),
        migrations.DeleteModel(
            name='Administration',
        ),
        migrations.DeleteModel(
            name='JournalAdmin',
        ),
    ]
