# Generated by Django 5.2.10 on 2026-03-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_restore_administration_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administration',
            name='niveau_accreditation',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='permissions_speciales',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='zone_responsabilite',
        ),
        migrations.RemoveField(
            model_name='journaladmin',
            name='administration',
        ),
        migrations.DeleteModel(
            name='NiveauAccreditation',
        ),
        migrations.DeleteModel(
            name='PermissionSpeciale',
        ),
        migrations.DeleteModel(
            name='ZoneResponsabilite',
        ),
        migrations.DeleteModel(
            name='Administration',
        ),
        migrations.DeleteModel(
            name='JournalAdmin',
        ),
    ]
