# Generated by Django 5.2.10 on 2026-03-10 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_create_groupe_personnel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CC', 'Contrôle Continu'), ('Examen Final', 'Examen Final')], max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('module', models.CharField(max_length=150, verbose_name='Module')),
                ('filiere', models.CharField(max_length=150, verbose_name='Filière')),
                ('annee', models.CharField(max_length=20, verbose_name='Année universitaire')),
                ('session', models.CharField(blank=True, default='Normale', max_length=20)),
                ('semestre', models.CharField(blank=True, default='S1', max_length=10)),
                ('remarque', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='archives_pdf/')),
                ('date_archive', models.DateField(auto_now_add=True, verbose_name='Archivé le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Archives',
            },
        ),
    ]
