# Generated by Django 5.x on 2026-03-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


GROUPE_ETUDIANT = "Étudiant"
GROUPE_ASSISTANT = "Assistant pédagogique"
GROUPE_ADMIN_SYSTEME = "Administrateur système"


def create_groupes_et_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    # Nettoyage compat: ancien groupe non utilisé
    Group.objects.filter(name="Personnel").delete()

    etudiant_group, _ = Group.objects.get_or_create(name=GROUPE_ETUDIANT)
    assistant_group, _ = Group.objects.get_or_create(name=GROUPE_ASSISTANT)
    admin_group, _ = Group.objects.get_or_create(name=GROUPE_ADMIN_SYSTEME)

    # Permissions "métier" (CRUD) pour l'assistant pédagogique.
    # La restriction "uniquement sa filière" se fait au niveau des vues/querysets.
    allowed_codenames = {
        # Examen
        "add_examen",
        "change_examen",
        "delete_examen",
        "view_examen",
        # Document
        "add_document",
        "change_document",
        "delete_document",
        "view_document",
        # Archive (tableau de bord / PDF)
        "add_archive",
        "change_archive",
        "delete_archive",
        "view_archive",
    }
    assistant_perms = Permission.objects.filter(codename__in=allowed_codenames)
    assistant_group.permissions.set(assistant_perms)

    # Admin système: toutes les permissions (tous apps) sur la plateforme.
    admin_group.permissions.set(Permission.objects.all())

    # Étudiant: pas de permissions particulières par défaut (lecture publique gérée par les vues).
    etudiant_group.permissions.clear()


def remove_groupes_et_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=[GROUPE_ETUDIANT, GROUPE_ASSISTANT, GROUPE_ADMIN_SYSTEME]).delete()
    # Ancien groupe (compat) : on le supprime si présent
    Group.objects.filter(name="Personnel").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_typeexamen_document_archive_document_principal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantPedagogique",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "filiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assistants_pedagogiques",
                        to="accounts.filiere",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_pedagogique",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assistant pédagogique",
                "verbose_name_plural": "Assistants pédagogiques",
            },
        ),
        migrations.RunPython(create_groupes_et_permissions, remove_groupes_et_permissions),
    ]

