# Generated by Django 5.2.10 on 2026-03-11 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_assistant_pedagogique_groupes_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Année académique',
                'verbose_name_plural': 'Années académiques',
            },
        ),
        migrations.RemoveField(
            model_name='archive',
            name='document_principal',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='document',
            name='examen',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='niveau',
        ),
        migrations.AddField(
            model_name='filiere',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Filière parent (ex : Physique-Chimie pour Physique / Chimie).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sous_filieres', to='accounts.filiere'),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='accounts.examen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vue', models.DateTimeField(auto_now_add=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='accounts.examen')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de consultation',
                'verbose_name_plural': 'Historiques de consultation',
                'ordering': ['-date_vue'],
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcours', to='accounts.anneeacademique')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcours', to='accounts.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcours', to='accounts.niveau')),
            ],
            options={
                'verbose_name': 'Parcours',
                'verbose_name_plural': 'Parcours',
            },
        ),
        migrations.AddField(
            model_name='examen',
            name='parcours',
            field=models.ManyToManyField(help_text='Parcours concernés par cet examen (commun ou spécifique).', related_name='examens', to='accounts.parcours'),
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='accounts.examen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'unique_together': {('user', 'examen')},
            },
        ),
        migrations.AddConstraint(
            model_name='parcours',
            constraint=models.UniqueConstraint(fields=('filiere', 'niveau', 'annee_academique'), name='uniq_parcours_filiere_niveau_annee'),
        ),
    ]
