# Generated by Django 5.2.10 on 2026-03-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_anneeacademique_remove_archive_document_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='archives_pdf/'),
        ),
    ]
