# Generated by Django 6.0.3 on 2026-03-31 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_commentairearchive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='fichier_corrige',
            field=models.FileField(blank=True, help_text='Optionnel : corrigé type pour les étudiants.', null=True, upload_to='archives_corrige/', verbose_name='Fichier corrigé (PDF)'),
        ),
        migrations.CreateModel(
            name='NoteArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField()),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_utilisateur', to='accounts.archive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_archives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note sur archive',
                'verbose_name_plural': 'Notes sur archives',
                'unique_together': {('user', 'archive')},
            },
        ),
    ]
