# Generated by Django 6.0.3 on 2026-03-24 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def activate_all_users(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    User.objects.filter(is_active=False).update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_commentairearchive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Présence utilisateur',
                'verbose_name_plural': 'Présences utilisateurs',
            },
        ),
        migrations.RunPython(activate_all_users, migrations.RunPython.noop),
    ]
