# Generated by Django 6.0.3 on 2026-03-31 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_archive_corrige_notearchive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationCorrigeGratuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_premier_acces', models.DateTimeField(auto_now_add=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_corrige_gratuits', to='accounts.archive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corriges_gratuits_consultes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accès corrigé gratuit',
                'verbose_name_plural': 'Accès corrigés gratuits',
                'unique_together': {('user', 'archive')},
            },
        ),
    ]
